"""ExtendScript (.jsx) batch PSD exporter.

Generates a single self-contained Adobe ExtendScript that, when run inside
Photoshop (File → Scripts → Browse), recreates the project's text blocks as
editable text layers across all selected pages and saves each page as PSD.

Mechanism (mirrors the LabelPlus PS-Script fork ZsIsMe/PS-Script):
- ``artLayers.add()`` + ``kind = LayerKind.TEXT`` + ``textItem.*`` DOM calls
- rotation via ``artLayer.rotate(-deg)`` — source data (BallonsTranslator) is
  CCW+, Photoshop is CW+, so the sign is flipped
- stroke / drop shadow via layer-style ActionDescriptor (``frameFX`` /
  ``dropShadow``)
- center-align fallback: translate the layer so its bounds center equals the
  block box center, compensating for PS-vs-local font-metric differences

The page data (Meo-style JSON) is embedded directly into the .jsx so there is
no external file / BOM / encoding dance at run time.  The output file itself
is written UTF-8 with BOM, matching the LabelPlus PS-Script distribution
convention for non-ASCII ExtendScript sources.
"""

import json
import logging
import math
import os
from string import Template
from typing import Dict, List, Optional, Set, Tuple

from .font_mapping import resolve_font_name
from .fontformat import LineSpacingType
from .proj_imgtrans import ProjImgTrans
from .psd_exporter import AbstractPsdExporter, ExportOptions

logger = logging.getLogger(__name__)

# ==============================================================================
# ExtendScript template
# ==============================================================================
# The template uses Python string.Template placeholders:
#   $machine_name — host name (header comment)
#   $project_name — project name (header comment)
#   $page_count   — number of pages (header comment)
#   $pages_json   — JSON payload object (embedded JS literal)
#   $font_notes   — JS comments about font compatibility
#
# IMPORTANT: the JS code must not contain a literal "$", otherwise
# string.Template treats it as a placeholder.
# ==============================================================================

BATCH_SCRIPT_TEMPLATE = Template(
    r"""#target photoshop
// =============================================================================
// Auto-generated by BallonsTranslator — batch PSD exporter (ExtendScript)
//
// Recreates the project's text blocks as editable text layers, one PSD per
// page.  Run once in Photoshop:  File → Scripts → Browse → select this file.
//
// Machine:  $machine_name
// Project:  $project_name
// Pages:    $page_count
// =============================================================================

app.bringToFront();

// --- helpers ----------------------------------------------------------------

function makeSolidColor(r, g, b) {
    var c = new SolidColor();
    c.rgb.red   = r;
    c.rgb.green = g;
    c.rgb.blue  = b;
    return c;
}

// Stroke (frameFX) + drop shadow via layer-style ActionDescriptor.
function applyLayerEffects(layer, blk) {
    try {
        var hasStroke = blk.stroke_size > 0;
        var hasShadow = blk.shadow_opacity > 0 && blk.shadow_blur > 0;
        if (!hasStroke && !hasShadow) return;

        var desc = new ActionDescriptor();
        var ref = new ActionReference();
        ref.putEnumerated(charIDToTypeID("Lyr "), charIDToTypeID("Ordn"), charIDToTypeID("Trgt"));
        desc.putReference(charIDToTypeID("null"), ref);

        var layerEffects = new ActionDescriptor();

        if (hasStroke) {
            var strokeDesc = new ActionDescriptor();
            strokeDesc.putBoolean(stringIDToTypeID("enabled"), true);
            strokeDesc.putEnumerated(stringIDToTypeID("style"), stringIDToTypeID("frameStyle"), stringIDToTypeID("outsetFrame"));
            strokeDesc.putUnitDouble(stringIDToTypeID("size"), charIDToTypeID("#Pxl"), blk.stroke_size);
            var sc = new ActionDescriptor();
            sc.putDouble(charIDToTypeID("Rd  "), blk.stroke_color[0]);
            sc.putDouble(charIDToTypeID("Grn "), blk.stroke_color[1]);
            sc.putDouble(charIDToTypeID("Bl  "), blk.stroke_color[2]);
            strokeDesc.putObject(stringIDToTypeID("color"), charIDToTypeID("RGBC"), sc);
            layerEffects.putObject(stringIDToTypeID("frameFX"), stringIDToTypeID("frameFX"), strokeDesc);
        }

        if (hasShadow) {
            var shadowDesc = new ActionDescriptor();
            shadowDesc.putBoolean(stringIDToTypeID("enabled"), true);
            shadowDesc.putEnumerated(stringIDToTypeID("mode"), charIDToTypeID("BlnM"), charIDToTypeID("Mltp"));
            shadowDesc.putUnitDouble(stringIDToTypeID("opacity"), charIDToTypeID("#Prc"), blk.shadow_opacity);
            shadowDesc.putBoolean(stringIDToTypeID("useGlobalAngle"), false);
            shadowDesc.putUnitDouble(stringIDToTypeID("localLightingAngle"), charIDToTypeID("#Ang"), blk.shadow_angle);
            shadowDesc.putUnitDouble(stringIDToTypeID("angle"), charIDToTypeID("#Ang"), blk.shadow_angle);
            shadowDesc.putUnitDouble(stringIDToTypeID("blur"), charIDToTypeID("#Pxl"), blk.shadow_blur);
            shadowDesc.putUnitDouble(stringIDToTypeID("distance"), charIDToTypeID("#Pxl"), blk.shadow_distance);
            var sc2 = new ActionDescriptor();
            sc2.putDouble(charIDToTypeID("Rd  "), blk.shadow_color[0]);
            sc2.putDouble(charIDToTypeID("Grn "), blk.shadow_color[1]);
            sc2.putDouble(charIDToTypeID("Bl  "), blk.shadow_color[2]);
            shadowDesc.putObject(stringIDToTypeID("color"), charIDToTypeID("RGBC"), sc2);
            layerEffects.putObject(stringIDToTypeID("dropShadow"), stringIDToTypeID("dropShadow"), shadowDesc);
        }

        desc.putObject(charIDToTypeID("T   "), stringIDToTypeID("layerEffects"), layerEffects);
        executeAction(charIDToTypeID("setd"), desc, DialogModes.NO);
    } catch (e) {}
}

// Create one editable text layer mirroring a project text block.
function createTextLayer(doc, blk) {
    var art = doc.artLayers.add();
    art.name = blk.name;
    art.kind = LayerKind.TEXT;
    var ti = art.textItem;

    try { ti.kind = TextType.POINT_TEXT; } catch (e) {}

    // Direction must be set BEFORE contents for reliable vertical text.
    if (blk.vertical) { try { ti.direction = Direction.VERTICAL; } catch (e) {} }

    ti.contents = blk.text;

    if (blk.font) { try { ti.font = blk.font; } catch (e) {} }
    if (blk.size_pt > 0) { try { ti.size = blk.size_pt; } catch (e) {} }
    try { ti.color = makeSolidColor(blk.color[0], blk.color[1], blk.color[2]); } catch (e) {}

    if (blk.bold)   { try { ti.fauxBold = true; } catch (e) {} }
    if (blk.italic) { try { ti.fauxItalic = true; } catch (e) {} }
    if (blk.underline) { try { ti.underline = true; } catch (e) {} }

    var alignMap = {0: Justification.LEFT, 1: Justification.CENTER, 2: Justification.RIGHT};
    try { ti.justification = alignMap[blk.alignment] || Justification.LEFT; } catch (e) {}

    // Line spacing → auto-leading percentage.
    if (blk.line_spacing > 0) {
        try { ti.useAutoLeading = true; ti.autoLeadingAmount = blk.line_spacing; } catch (e) {}
    }

    // Initial position near the block box (center-align corrects below).
    // Explicit px units — bare numbers would follow the current ruler unit.
    if (blk.vertical) {
        try { ti.position = [UnitValue(blk.box[2], 'px'), UnitValue(blk.box[1], 'px')]; } catch (e) {}
    } else {
        try { ti.position = [UnitValue(blk.box[0], 'px'), UnitValue(blk.box[1] + blk.size_px * 0.8, 'px')]; } catch (e) {}
    }

    if (blk.opacity < 1.0) { try { art.opacity = blk.opacity * 100; } catch (e) {} }

    // Rotation — BallonsTranslator is CCW+, Photoshop is CW+, so negate.
    if (blk.rotation) {
        try { art.rotate(-blk.rotation, AnchorPosition.MIDDLECENTER); } catch (e) {}
    }

    applyLayerEffects(art, blk);

    // Center-align fallback: shift the layer so its bounds center matches the
    // block box center, absorbing PS-vs-local font-metric differences.
    if (blk.center) {
        var ru = app.preferences.rulerUnits;
        app.preferences.rulerUnits = Units.PIXELS;
        try {
            var b = art.bounds;
            var w = b[2].as('px') - b[0].as('px');
            var h = b[3].as('px') - b[1].as('px');
            var cx = (blk.box[0] + blk.box[2]) / 2;
            var cy = (blk.box[1] + blk.box[3]) / 2;
            var curx = b[0].as('px') + w / 2;
            var cury = b[1].as('px') + h / 2;
            art.translate(UnitValue(cx - curx, 'px'), UnitValue(cy - cury, 'px'));
        } catch (e) {}
        finally { app.preferences.rulerUnits = ru; }
    }

    return art;
}

// Open one source image, add its text layers, save PSD.
function processPage(page) {
    var src = File(page.path);
    if (!src.exists) {
        alert("Missing source image:\n" + page.path);
        return false;
    }
    var doc = app.open(src);
    app.activeDocument = doc;

    // Normalize resolution so pt→px sizing matches the export-time computation.
    try { doc.resizeImage(undefined, undefined, page.dpi); } catch (e) {}

    for (var i = 0; i < page.blocks.length; i++) {
        try { createTextLayer(doc, page.blocks[i]); } catch (e) {}
    }

    var psdFile = File(page.out_path);
    var opts = new PhotoshopSaveOptions();
    opts.embedColorProfile = true;
    doc.saveAs(psdFile, opts, true);
    doc.close(SaveOptions.DONOTSAVECHANGES);
    return true;
}

// --- main -------------------------------------------------------------------

$font_notes

var DATA = $pages_json;

var done = 0;
var skipped = 0;
for (var p = 0; p < DATA.pages.length; p++) {
    if (processPage(DATA.pages[p])) { done++; }
    else { skipped++; }
}

var summary = "Exported " + done + " / " + DATA.pages.length + " PSD file(s).";
if (skipped > 0) { summary += "\n" + skipped + " page(s) skipped (missing image)."; }
alert(summary);
"""
)

# ==============================================================================
# Exporter
# ==============================================================================


class PsJsxExporter(AbstractPsdExporter):
    """Produce a single self-contained .jsx that rebuilds text layers in PS.

    No Photoshop dependency at export time — the script is plain text.
    """

    # ------------------------------------------------------------------
    # AbstractPsdExporter
    # ------------------------------------------------------------------

    def check_availability(self, passive: bool = False) -> Tuple[bool, str]:
        # Always available — JSX is plain-text output.
        return True, "ExtendScript can be run on any machine with Photoshop"

    def get_available_fonts(self) -> Set[str]:
        # We cannot enumerate PS fonts without COM.
        return set()

    def export_page(
        self,
        proj: ProjImgTrans,
        page_name: str,
        options: ExportOptions,
    ) -> str:
        """Export a single page as its own .jsx (interface compatibility)."""
        return self.export_batch(proj, [page_name], options)

    def export_batch(
        self,
        proj: ProjImgTrans,
        page_names: List[str],
        options: ExportOptions,
    ) -> str:
        """Generate ONE .jsx covering all *page_names*; returns its path.

        Run the resulting script once in Photoshop (File → Scripts → Browse)
        to recreate every page as an editable-text PSD.
        """
        os.makedirs(options.output_dir, exist_ok=True)

        pages = self._build_pages(proj, page_names, options)

        script = BATCH_SCRIPT_TEMPLATE.substitute(
            machine_name=os.environ.get("COMPUTERNAME", "unknown"),
            project_name=proj.proj_name(),
            page_count=len(page_names),
            pages_json=json.dumps(
                {"pages": pages}, ensure_ascii=False, separators=(",", ":")
            ),
            font_notes=self._build_font_notes(proj, page_names),
        )

        jsx_path = os.path.join(
            options.output_dir, proj.proj_name() + "_psd_export.jsx"
        )
        # UTF-8 with BOM — required for non-ASCII ExtendScript sources.
        with open(jsx_path, "w", encoding="utf-8-sig", newline="\n") as f:
            f.write(script)

        logger.info(
            "PSD export script written to %s (%d pages)", jsx_path, len(page_names)
        )
        return jsx_path

    def cleanup(self):
        pass  # nothing to release

    # ------------------------------------------------------------------
    # internal — payload construction
    # ------------------------------------------------------------------

    @staticmethod
    def _build_pages(
        proj: ProjImgTrans,
        page_names: List[str],
        options: ExportOptions,
    ) -> List[Dict]:
        """Build the per-page payload embedded in the .jsx."""
        pages: List[Dict] = []
        for page_name in page_names:
            src = os.path.join(proj.directory, page_name)
            dpi = PsJsxExporter._read_image_dpi(src)

            blocks = []
            for idx, blk in enumerate(proj.pages.get(page_name, []), 1):
                if not blk.translation or not blk.translation.strip():
                    continue
                blocks.append(
                    PsJsxExporter._block_payload(blk, idx, dpi, options.center_align)
                )

            pages.append(
                {
                    "name": page_name,
                    "path": PsJsxExporter._js_path(src),
                    "dpi": dpi,
                    "out_path": PsJsxExporter._js_path(
                        os.path.join(
                            options.output_dir,
                            os.path.splitext(page_name)[0] + ".psd",
                        )
                    ),
                    "blocks": blocks,
                }
            )
        return pages

    @staticmethod
    def _block_payload(blk, index: int, dpi: float, center: bool) -> Dict:
        """Convert one TextBlock → the JS layer descriptor dict."""
        ff = blk.fontformat
        x1, y1, x2, y2 = blk.xyxy
        font_size = float(ff.font_size) if ff.font_size else 1.0

        resolved, _ = resolve_font_name(ff.font_family, ps_available=None)

        # Point size so the rendered pixel height matches the source block:
        #   pt = px * 72 / image_dpi    (PS renders pt at the doc resolution)
        size_pt = round(font_size * 72.0 / dpi, 2)

        # Line spacing → PS auto-leading percentage.
        if ff.line_spacing_type == LineSpacingType.Distance and font_size > 0:
            line_spacing = round(float(ff.line_spacing) / font_size * 100.0, 2)
        else:
            line_spacing = round(float(ff.line_spacing) * 100.0, 2)

        # Stroke pen width (matches effect_renderer: font_size × stroke_width).
        stroke_width = float(ff.stroke_width) if ff.stroke_width else 0.0
        stroke_size = round(font_size * stroke_width, 2) if stroke_width > 0 else 0.0

        # Shadow blur / distance / opacity (matches effect_renderer formulas).
        shadow_radius = float(ff.shadow_radius) if ff.shadow_radius else 0.0
        shadow_strength = float(ff.shadow_strength) if ff.shadow_strength else 0.0
        ox, oy = (float(v) for v in ff.shadow_offset)
        if shadow_radius > 0 and shadow_strength > 0:
            shadow_blur = round(shadow_radius * font_size, 2)
            shadow_opacity = int(shadow_strength * 100)
            shadow_distance = round(math.hypot(ox, oy) * font_size, 2)
            # PS interprets the angle as the LIGHT source; shadow falls opposite
            # the offset, hence the 180° flip.
            shadow_angle = round(
                (math.degrees(math.atan2(-oy, ox)) + 180.0) % 360.0, 2
            )
        else:
            shadow_blur = 0.0
            shadow_opacity = 0
            shadow_distance = 0.0
            shadow_angle = 0.0

        return {
            "name": (
                f"TL {index:03d} "
                f"{blk.translation[:20].replace(chr(10), ' ').replace(chr(13), ' ')}"
            ),
            "text": blk.translation.strip(),
            "font": resolved,
            "size_pt": size_pt,
            "size_px": round(font_size, 2),
            "color": ff.foreground_color(),
            "bold": bool(ff.bold),
            "italic": bool(ff.italic),
            "underline": bool(ff.underline),
            "vertical": bool(ff.vertical),
            "alignment": int(ff.alignment),
            "opacity": float(ff.opacity) if ff.opacity is not None else 1.0,
            "line_spacing": line_spacing,
            "box": [round(float(v), 1) for v in (x1, y1, x2, y2)],
            "stroke_size": stroke_size,
            "stroke_color": ff.stroke_color() if stroke_width > 0 else [0, 0, 0],
            "shadow_blur": shadow_blur,
            "shadow_opacity": shadow_opacity,
            "shadow_distance": shadow_distance,
            "shadow_angle": shadow_angle,
            "shadow_color": list(ff.shadow_color),
            "rotation": round(float(blk.angle), 2),
            "center": bool(center),
        }

    @staticmethod
    def _build_font_notes(proj: ProjImgTrans, page_names: List[str]) -> str:
        """Generate JS comments noting which fonts may need manual adjustment."""
        families: List[str] = []
        for page_name in page_names:
            for blk in proj.pages.get(page_name, []):
                fam = blk.fontformat.font_family
                if fam and fam not in families:
                    families.append(fam)

        lines = ["// Font compatibility notes:"]
        for fam in sorted(families):
            mapped, _ = resolve_font_name(fam, ps_available=None)
            if mapped != fam:
                lines.append(f"//   '{fam}' → '{mapped}' (auto-mapped)")
            else:
                lines.append(
                    f"//   '{fam}' — verify this font is installed in Photoshop"
                )
        lines.append("//")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # internal — helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _read_image_dpi(img_path: str) -> float:
        """Read the DPI of a source image using PIL; 96.0 as fallback."""
        try:
            from PIL import Image as PILImage

            with PILImage.open(img_path) as img:
                dpi_info = img.info.get("dpi")
                if dpi_info and len(dpi_info) >= 2:
                    dpi = max(dpi_info[0], dpi_info[1], 72.0)
                    logger.debug("Image DPI: %.1f (from %s)", dpi, img_path)
                    return dpi
        except Exception:
            pass
        logger.debug("Could not read DPI from '%s', falling back to 96.0", img_path)
        return 96.0

    @staticmethod
    def _js_path(path: str) -> str:
        """ExtendScript accepts forward slashes on Windows too."""
        return path.replace("\\", "/")
