"""ExtendScript (.jsx) PSD generator.

Generates a self-contained Adobe ExtendScript that, when run inside
Photoshop (File → Scripts → Browse), creates a PSD with editable text
layers matching the BallonsTranslator project.

No PS dependency at export time — just Python stdlib.
"""

import json
import logging
import math
import os
import shutil
from string import Template
from typing import Dict, List, Optional, Set, Tuple

from .font_mapping import QT_TO_PS_FONT_MAP, resolve_font_name
from .proj_imgtrans import ProjImgTrans
from .psd_exporter import AbstractPsdExporter, ExportOptions

logger = logging.getLogger(__name__)

# ==============================================================================
# ExtendScript template
# ==============================================================================
# The template uses Python string.Template placeholders:
#   $image_path   — absolute path to source image
#   $psd_path     — absolute path for output PSD
#   $layers_json  — JSON array of text layer descriptors (injected as JS literal)
# ==============================================================================

PAGE_SCRIPT_TEMPLATE = Template(
    r"""
// =============================================================================
// Auto-generated by BallonsTranslator — ExtendScript PSD exporter
//
// Run in Photoshop:  File → Scripts → Browse → select this file
//
// NOTE: Font sizes (size_pt) are derived from the source image's actual DPI.
//
// Machine: $machine_name
// Page:    $page_name
// Blocks:  $block_count
// =============================================================================

#target photoshop
app.bringToFront();

// --- helpers ----------------------------------------------------------------
function makeSolidColor(r, g, b) {
    var c = new SolidColor();
    c.rgb.red   = r;
    c.rgb.green = g;
    c.rgb.blue  = b;
    return c;
}

function applyLayerEffects(layer, strokeSize, strokeColor, shadowOpacity, shadowBlur, shadowDistance, shadowColor, shadowAngle) {
    try {
        var hasStroke = strokeSize > 0;
        var hasShadow = shadowOpacity > 0 && shadowBlur > 0;
        if (!hasStroke && !hasShadow) return;

        var desc = new ActionDescriptor();
        var ref = new ActionReference();
        ref.putEnumerated(charIDToTypeID("Lyr "), charIDToTypeID("Ordn"), charIDToTypeID("Trgt"));
        desc.putReference(charIDToTypeID("null"), ref);

        var layerEffects = new ActionDescriptor();

        if (hasStroke) {
            var strokeDesc = new ActionDescriptor();
            strokeDesc.putBoolean(stringIDToTypeID("enabled"), true);
            strokeDesc.putEnumerated(stringIDToTypeID("style"), stringIDToTypeID("frameStyle"), stringIDToTypeID("outsetFrame"));
            strokeDesc.putUnitDouble(stringIDToTypeID("size"), charIDToTypeID("#Pxl"), strokeSize);
            var sc = new ActionDescriptor();
            sc.putDouble(charIDToTypeID("Rd  "), strokeColor[0]);
            sc.putDouble(charIDToTypeID("Grn "), strokeColor[1]);
            sc.putDouble(charIDToTypeID("Bl  "), strokeColor[2]);
            strokeDesc.putObject(stringIDToTypeID("color"), charIDToTypeID("RGBC"), sc);
            layerEffects.putObject(stringIDToTypeID("frameFX"), stringIDToTypeID("frameFX"), strokeDesc);
        }

        if (hasShadow) {
            var shadowDesc = new ActionDescriptor();
            shadowDesc.putBoolean(stringIDToTypeID("enabled"), true);
            shadowDesc.putEnumerated(stringIDToTypeID("mode"), charIDToTypeID("BlnM"), charIDToTypeID("Mltp"));
            shadowDesc.putUnitDouble(stringIDToTypeID("opacity"), charIDToTypeID("#Prc"), shadowOpacity);
            shadowDesc.putBoolean(stringIDToTypeID("useGlobalAngle"), false);
            shadowDesc.putUnitDouble(stringIDToTypeID("localLightingAngle"), charIDToTypeID("#Ang"), shadowAngle);
            shadowDesc.putUnitDouble(stringIDToTypeID("angle"), charIDToTypeID("#Ang"), shadowAngle);
            shadowDesc.putUnitDouble(stringIDToTypeID("blur"), charIDToTypeID("#Pxl"), shadowBlur);
            shadowDesc.putUnitDouble(stringIDToTypeID("distance"), charIDToTypeID("#Pxl"), shadowDistance);
            var sc = new ActionDescriptor();
            sc.putDouble(charIDToTypeID("Rd  "), shadowColor[0]);
            sc.putDouble(charIDToTypeID("Grn "), shadowColor[1]);
            sc.putDouble(charIDToTypeID("Bl  "), shadowColor[2]);
            shadowDesc.putObject(stringIDToTypeID("color"), charIDToTypeID("RGBC"), sc);
            layerEffects.putObject(stringIDToTypeID("dropShadow"), stringIDToTypeID("dropShadow"), shadowDesc);
        }

        desc.putObject(charIDToTypeID("T   "), stringIDToTypeID("layerEffects"), layerEffects);
        executeAction(charIDToTypeID("setd"), desc, DialogModes.NO);
    } catch(e) {}
}

// --- main -------------------------------------------------------------------

var layers = $layers_json;
var srcFile = File($escaped_image_path);
if (!srcFile.exists) {
    alert("Source image not found:\\n" + $escaped_image_path);
    throw new Error("Missing source image");
}

var doc = app.open(srcFile);
app.activeDocument = doc;

// Font availability notes (pre-computed by BallonsTranslator):
$font_notes

for (var i = 0; i < layers.length; i++) {
    var lyr = layers[i];
    var artLayer = doc.artLayers.add();
    artLayer.name = lyr.name;
    artLayer.kind = LayerKind.TEXT;

    var ti = artLayer.textItem;

    // Point Text — more reliable for both orientations than Paragraph Text,
    // and allows precise positioning (paragraph text auto-wraps at unknown bounds).
    try { ti.kind = TextType.POINT_TEXT; } catch(e) {}

    // Direction must be set BEFORE contents for reliable vertical text
    if (lyr.vertical) {
        try { ti.direction = Direction.VERTICAL; } catch(e) {}
    }

    ti.contents = lyr.text;

    // Font — may require manual adjustment if font is not installed
    try { ti.font = lyr.font; } catch(e) {}

    // Size
    try { ti.size = lyr.size_pt; } catch(e) {}

    // Color
    try { ti.color = makeSolidColor(lyr.color[0], lyr.color[1], lyr.color[2]); } catch(e) {}

    // Style
    if (lyr.bold)  try { ti.fauxBold = true; } catch(e) {}
    if (lyr.italic) try { ti.fauxItalic = true; } catch(e) {}
    if (lyr.underline) try { ti.underline = true; } catch(e) {}

    // Alignment — Justification.LEFT (1), Justification.CENTER (2), Justification.RIGHT (3)
    var alignMap = {0: Justification.LEFT, 1: Justification.CENTER, 2: Justification.RIGHT};
    try { ti.justification = alignMap[lyr.alignment] || Justification.LEFT; } catch(e) {}

    // Position — horizontal uses [left_edge, baseline_y], vertical uses [column_right, top]
    try { ti.position = [lyr.pos_x, lyr.pos_y]; } catch(e) {}

    // Layer opacity
    if (lyr.opacity < 1.0) {
        try { artLayer.opacity = lyr.opacity * 100; } catch(e) {}
    }

    // Layer effects (stroke + drop shadow in one Action Manager call)
    if (lyr.stroke_size > 0 || (lyr.shadow_blur > 0 && lyr.shadow_opacity > 0)) {
        applyLayerEffects(artLayer, lyr.stroke_size, lyr.stroke_color, lyr.shadow_opacity, lyr.shadow_blur, lyr.shadow_distance, lyr.shadow_color, lyr.shadow_angle);
    }
}

// --- save PSD ---------------------------------------------------------------

var psdFile = File($escaped_psd_path);
var psdOpts = new PhotoshopSaveOptions();
psdOpts.embedColorProfile = true;
doc.saveAs(psdFile, psdOpts, true);
doc.close(SaveOptions.DONOTSAVECHANGES);

"Done — saved: " + psdFile.fsName;
"""
)

# ==============================================================================
# Exporter
# ==============================================================================


class PsJsxExporter(AbstractPsdExporter):
    """ExtendScript (.jsx) generation — no PS dependency at export time."""

    # ------------------------------------------------------------------
    # AbstractPsdExporter
    # ------------------------------------------------------------------

    def check_availability(self, passive: bool = False) -> Tuple[bool, str]:
        # Always available — JSX is plain-text output.
        return True, "ExtendScript can be run on any machine with Photoshop"

    def get_available_fonts(self) -> Set[str]:
        # We cannot enumerate PS fonts without COM.
        return set()

    def export_page(
        self,
        proj: ProjImgTrans,
        page_name: str,
        options: ExportOptions,
    ) -> str:
        os.makedirs(options.output_dir, exist_ok=True)

        # Copy source image alongside the .jsx so it's portable
        src = os.path.join(proj.directory, page_name)
        dst_img = os.path.join(options.output_dir, page_name)
        if not os.path.exists(dst_img) or not os.path.samefile(src, dst_img):
            shutil.copy2(src, dst_img)

        # Read source image DPI for correct font sizing in PS
        dpi = self._read_image_dpi(src)

        # Collect block data
        layers = self._build_layers(proj.pages.get(page_name, []), dpi=dpi)

        # Font notes
        font_notes = self._build_font_notes(proj, page_name)

        # Render template
        base, _ = os.path.splitext(page_name)
        script = PAGE_SCRIPT_TEMPLATE.substitute(
            machine_name=os.environ.get("COMPUTERNAME", "unknown"),
            page_name=page_name,
            block_count=len(layers),
            layers_json=json.dumps(layers, ensure_ascii=False, indent=2),
            escaped_image_path=json.dumps(os.path.abspath(dst_img)),
            escaped_psd_path=json.dumps(
                os.path.abspath(os.path.join(options.output_dir, f"{base}.psd"))
            ),
            font_notes=font_notes,
        )

        jsx_path = os.path.join(options.output_dir, f"{base}.jsx")
        with open(jsx_path, "w", encoding="utf-8") as f:
            f.write(script)

        return jsx_path

    def cleanup(self):
        pass  # nothing to release

    # ------------------------------------------------------------------
    # internal
    # ------------------------------------------------------------------

    @staticmethod
    def _read_image_dpi(img_path: str) -> float:
        """Read the DPI of a source image using PIL.

        Returns the DPI value, or 96.0 as fallback.
        """
        try:
            from PIL import Image as PILImage

            with PILImage.open(img_path) as img:
                dpi_info = img.info.get("dpi")
                if dpi_info and len(dpi_info) >= 2:
                    dpi = max(dpi_info[0], dpi_info[1], 72.0)
                    logger.debug("Image DPI: %.1f (from %s)", dpi, img_path)
                    return dpi
        except Exception:
            pass
        logger.debug("Could not read DPI from '%s', falling back to 96.0", img_path)
        return 96.0

    @staticmethod
    def _build_layers(blk_list: List, dpi: float = 96.0) -> List[Dict]:
        """Convert TextBlock list → list of JS layer dicts.

        Args:
            blk_list: text blocks for this page.
            dpi: DPI of the source image, used to compute correct font point sizes.
        """
        layers = []
        for idx, blk in enumerate(blk_list):
            if not blk.translation:
                continue
            ff = blk.fontformat
            x1, y1, x2, y2 = blk.xyxy

            # Resolve font (static map only — no PS font list available)
            resolved, _ = resolve_font_name(ff.font_family, ps_available=None)

            # Font size in points — correct for source image's DPI.
            # ff.font_size is in image pixels (from text detection), so
            #   size_pt = image_px * 72 / image_dpi   gives the right point size.
            size_pt = ff.font_size * 72.0 / dpi

            # Position:
            #   - Horizontal: PS expects [left_edge, baseline_y].
            #     Shift y below the visual top by ~82% of font height (font-dependent).
            #   - Vertical:   PS expects [column_right_edge, top_of_first_char],
            #     because CJK vertical text flows columns right-to-left.
            if ff.vertical:
                pos_x = x2
                pos_y = y1
            else:
                pos_x = x1
                pos_y = y1 + ff.font_size * 0.82

            # Shadow angle — PS Action Manager interprets this as the LIGHT angle
            # (where the light comes from). The shadow falls in the opposite direction
            # from the offset, so we add 180° to convert shadow-direction → light-direction.
            # PS convention: 0°=right, counterclockwise (standard math) for #Ang unit.
            ox, oy = ff.shadow_offset
            shadow_angle = (
                (math.degrees(math.atan2(-oy, ox)) + 180) % 360
                if ff.shadow_radius > 0
                else 0
            )

            # Shadow distance — match in-app rendering: offset * font_size (unitless ratio × font height)
            shadow_distance = (
                math.hypot(ox, oy) * ff.font_size
                if ff.shadow_radius > 0
                else 0
            )

            layers.append(
                {
                    "name": f"text_{idx:02d}_{blk.translation[:20].replace(chr(10),' ').replace(chr(13),'')}",
                    "text": blk.translation,
                    "font": resolved,
                    "size_pt": size_pt,
                    "color": ff.foreground_color(),
                    "bold": ff.bold,
                    "italic": ff.italic,
                    "underline": ff.underline,
                    "alignment": ff.alignment,
                    "vertical": ff.vertical,
                    "pos_x": pos_x,
                    "pos_y": pos_y,
                    "opacity": ff.opacity,
                    # stroke
                    "stroke_size": (
                        max(ff.stroke_width * ff.font_size * 0.5, 0.5)
                        if ff.stroke_width > 0
                        else 0
                    ),
                    "stroke_color": ff.stroke_color() if ff.stroke_width > 0 else [0, 0, 0],
                    # shadow
                    "shadow_blur": (
                        max(ff.shadow_radius * ff.font_size, 0.5)
                        if ff.shadow_radius > 0
                        else 0
                    ),
                    "shadow_opacity": (
                        int(ff.shadow_strength * 100)
                        if ff.shadow_strength > 0
                        else 0
                    ),
                    "shadow_distance": shadow_distance,
                    "shadow_color": ff.shadow_color,
                    "shadow_angle": shadow_angle,
                }
            )

        return layers

    @staticmethod
    def _build_font_notes(proj: ProjImgTrans, page_name: str) -> str:
        """Generate JS comments noting which fonts may need manual adjustment."""
        blk_list = proj.pages.get(page_name, [])
        families: Set[str] = set()
        for blk in blk_list:
            families.add(blk.fontformat.font_family)

        lines = ["// Font compatibility notes:"]
        for fam in sorted(families):
            mapped = QT_TO_PS_FONT_MAP.get(fam, fam)
            if mapped != fam:
                lines.append(f"//   '{fam}' → '{mapped}' (auto-mapped)")
            else:
                lines.append(
                    f"//   '{fam}' — verify this font is installed in Photoshop"
                )
        lines.append("//")
        return "\n".join(lines)
