"""ExtendScript (.jsx) PSD generator.

Generates a self-contained Adobe ExtendScript that, when run inside
Photoshop (File → Scripts → Browse), creates a PSD with editable text
layers matching the BallonsTranslator project.

No PS dependency at export time — just Python stdlib.
"""

import json
import logging
import math
import os
import shutil
from string import Template
from typing import Dict, List, Optional, Set, Tuple

from .font_mapping import QT_TO_PS_FONT_MAP, resolve_font_name
from .proj_imgtrans import ProjImgTrans
from .psd_exporter import AbstractPsdExporter, ExportOptions

logger = logging.getLogger(__name__)

# ==============================================================================
# ExtendScript template
# ==============================================================================
# The template uses Python string.Template placeholders:
#   $image_path   — absolute path to source image
#   $psd_path     — absolute path for output PSD
#   $layers_json  — JSON array of text layer descriptors (injected as JS literal)
# ==============================================================================

PAGE_SCRIPT_TEMPLATE = Template(
    r"""
// =============================================================================
// Auto-generated by BallonsTranslator — ExtendScript PSD exporter
//
// Run in Photoshop:  File → Scripts → Browse → select this file
//
// NOTE: Font sizes (size_pt) are derived from the source image's actual DPI.
//
// Machine: $machine_name
// Page:    $page_name
// Blocks:  $block_count
// =============================================================================

#target photoshop
app.bringToFront();

// --- helpers ----------------------------------------------------------------
function makeSolidColor(r, g, b) {
    var c = new SolidColor();
    c.rgb.red   = r;
    c.rgb.green = g;
    c.rgb.blue  = b;
    return c;
}

function applyStroke(layer, sizePx, colorRGB) {
    try {
        var desc = new ActionDescriptor();
        var ref = new ActionReference();
        ref.putEnumerated(charIDToTypeID("Lyr "), charIDToTypeID("Ordn"), charIDToTypeID("Trgt"));
        desc.putReference(charIDToTypeID("null"), ref);
        // Enable layer FX
        var fxDesc = new ActionDescriptor();
        var fxRef = new ActionReference();
        fxRef.putProperty(charIDToTypeID("Prpr"), stringIDToTypeID("layerEffects"));
        fxRef.putEnumerated(charIDToTypeID("Lyr "), charIDToTypeID("Ordn"), charIDToTypeID("Trgt"));
        fxDesc.putReference(charIDToTypeID("null"), fxRef);

        // Stroke
        var strokeDesc = new ActionDescriptor();
        strokeDesc.putBoolean(stringIDToTypeID("enabled"), true);
        strokeDesc.putEnumerated(stringIDToTypeID("style"), stringIDToTypeID("frameStyle"), stringIDToTypeID("outsetFrame"));
        strokeDesc.putUnitDouble(stringIDToTypeID("size"), charIDToTypeID("#Pxl"), sizePx);
        var sc = new ActionDescriptor();
        sc.putDouble(charIDToTypeID("Rd  "), colorRGB[0]);
        sc.putDouble(charIDToTypeID("Grn "), colorRGB[1]);
        sc.putDouble(charIDToTypeID("Bl  "), colorRGB[2]);
        strokeDesc.putObject(stringIDToTypeID("color"), charIDToTypeID("RGBC"), sc);
        fxDesc.putObject(stringIDToTypeID("frameFX"), stringIDToTypeID("frameFX"), strokeDesc);

        executeAction(charIDToTypeID("setd"), fxDesc, DialogModes.NO);
    } catch(e) {}
}

function applyDropShadow(layer, opacityPct, blurPx, distancePx, colorRGB, angleDeg) {
    try {
        var desc = new ActionDescriptor();
        var ref = new ActionReference();
        ref.putEnumerated(charIDToTypeID("Lyr "), charIDToTypeID("Ordn"), charIDToTypeID("Trgt"));
        desc.putReference(charIDToTypeID("null"), ref);

        var fxDesc = new ActionDescriptor();
        var fxRef = new ActionReference();
        fxRef.putProperty(charIDToTypeID("Prpr"), stringIDToTypeID("layerEffects"));
        fxRef.putEnumerated(charIDToTypeID("Lyr "), charIDToTypeID("Ordn"), charIDToTypeID("Trgt"));
        fxDesc.putReference(charIDToTypeID("null"), fxRef);

        var shadowDesc = new ActionDescriptor();
        shadowDesc.putBoolean(stringIDToTypeID("enabled"), true);
        shadowDesc.putEnumerated(stringIDToTypeID("mode"), charIDToTypeID("BlnM"), charIDToTypeID("Mltp"));
        shadowDesc.putUnitDouble(stringIDToTypeID("opacity"), charIDToTypeID("#Prc"), opacityPct);
        shadowDesc.putBoolean(stringIDToTypeID("useGlobalAngle"), false);
        shadowDesc.putUnitDouble(stringIDToTypeID("localLightingAngle"), charIDToTypeID("#Ang"), angleDeg);
        shadowDesc.putUnitDouble(stringIDToTypeID("blur"), charIDToTypeID("#Pxl"), blurPx);
        shadowDesc.putUnitDouble(stringIDToTypeID("distance"), charIDToTypeID("#Pxl"), distancePx);
        var sc = new ActionDescriptor();
        sc.putDouble(charIDToTypeID("Rd  "), colorRGB[0]);
        sc.putDouble(charIDToTypeID("Grn "), colorRGB[1]);
        sc.putDouble(charIDToTypeID("Bl  "), colorRGB[2]);
        shadowDesc.putObject(stringIDToTypeID("color"), charIDToTypeID("RGBC"), sc);
        fxDesc.putObject(stringIDToTypeID("dropShadow"), stringIDToTypeID("dropShadow"), shadowDesc);

        executeAction(charIDToTypeID("setd"), fxDesc, DialogModes.NO);
    } catch(e) {}
}

// --- main -------------------------------------------------------------------

var layers = $layers_json;
var srcFile = File($escaped_image_path);
if (!srcFile.exists) {
    alert("Source image not found:\\n" + $escaped_image_path);
    throw new Error("Missing source image");
}

var doc = app.open(srcFile);
app.activeDocument = doc;

// Font availability notes (pre-computed by BallonsTranslator):
$font_notes

for (var i = 0; i < layers.length; i++) {
    var lyr = layers[i];
    var artLayer = doc.artLayers.add();
    artLayer.name = lyr.name;
    artLayer.kind = LayerKind.TEXT;

    var ti = artLayer.textItem;

    // Orientation must be set BEFORE contents for reliable vertical text
    if (lyr.vertical) {
        try { ti.orientation = 2; } catch(e) {}   // Orientation.VERTICAL
    }

    ti.contents = lyr.text;

    // Font — may require manual adjustment if font is not installed
    try { ti.font = lyr.font; } catch(e) {}

    // Size
    try { ti.size = lyr.size_pt; } catch(e) {}

    // Color
    try { ti.color = makeSolidColor(lyr.color[0], lyr.color[1], lyr.color[2]); } catch(e) {}

    // Style
    if (lyr.bold)  try { ti.fauxBold = true; } catch(e) {}
    if (lyr.italic) try { ti.fauxItalic = true; } catch(e) {}
    if (lyr.underline) try { ti.underline = true; } catch(e) {}

    // Alignment — PsJustification: psLeft=1, psCenter=2, psRight=3
    var alignMap = {0: 1, 1: 2, 2: 3};
    try { ti.justification = alignMap[lyr.alignment] || 1; } catch(e) {}

    // Position
    try { ti.position = [lyr.x, lyr.y]; } catch(e) {}

    // Layer opacity
    if (lyr.opacity < 1.0) {
        try { artLayer.opacity = lyr.opacity * 100; } catch(e) {}
    }

    // Stroke effect
    if (lyr.stroke_size > 0) {
        applyStroke(artLayer, lyr.stroke_size, lyr.stroke_color);
    }

    // Drop shadow
    if (lyr.shadow_blur > 0 && lyr.shadow_opacity > 0) {
        applyDropShadow(artLayer, lyr.shadow_opacity, lyr.shadow_blur, lyr.shadow_distance, lyr.shadow_color, lyr.shadow_angle);
    }
}

// --- save PSD ---------------------------------------------------------------

var psdFile = File($escaped_psd_path);
var psdOpts = new PhotoshopSaveOptions();
psdOpts.embedColorProfile = true;
doc.saveAs(psdFile, psdOpts, true);
doc.close(SaveOptions.DONOTSAVECHANGES);

"Done — saved: " + psdFile.fsName;
"""
)

# ==============================================================================
# Exporter
# ==============================================================================


class PsJsxExporter(AbstractPsdExporter):
    """ExtendScript (.jsx) generation — no PS dependency at export time."""

    # ------------------------------------------------------------------
    # AbstractPsdExporter
    # ------------------------------------------------------------------

    def check_availability(self, passive: bool = False) -> Tuple[bool, str]:
        # Always available — JSX is plain-text output.
        return True, "ExtendScript can be run on any machine with Photoshop"

    def get_available_fonts(self) -> Set[str]:
        # We cannot enumerate PS fonts without COM.
        return set()

    def export_page(
        self,
        proj: ProjImgTrans,
        page_name: str,
        options: ExportOptions,
    ) -> str:
        os.makedirs(options.output_dir, exist_ok=True)

        # Copy source image alongside the .jsx so it's portable
        src = os.path.join(proj.directory, page_name)
        dst_img = os.path.join(options.output_dir, page_name)
        if not os.path.exists(dst_img) or not os.path.samefile(src, dst_img):
            shutil.copy2(src, dst_img)

        # Read source image DPI for correct font sizing in PS
        dpi = self._read_image_dpi(src)

        # Collect block data
        layers = self._build_layers(proj.pages.get(page_name, []), dpi=dpi)

        # Font notes
        font_notes = self._build_font_notes(proj, page_name)

        # Render template
        base, _ = os.path.splitext(page_name)
        script = PAGE_SCRIPT_TEMPLATE.substitute(
            machine_name=os.environ.get("COMPUTERNAME", "unknown"),
            page_name=page_name,
            block_count=len(layers),
            layers_json=json.dumps(layers, ensure_ascii=False, indent=2),
            escaped_image_path=json.dumps(os.path.abspath(dst_img)),
            escaped_psd_path=json.dumps(
                os.path.abspath(os.path.join(options.output_dir, f"{base}.psd"))
            ),
            font_notes=font_notes,
        )

        jsx_path = os.path.join(options.output_dir, f"{base}.jsx")
        with open(jsx_path, "w", encoding="utf-8") as f:
            f.write(script)

        return jsx_path

    def cleanup(self):
        pass  # nothing to release

    # ------------------------------------------------------------------
    # internal
    # ------------------------------------------------------------------

    @staticmethod
    def _read_image_dpi(img_path: str) -> float:
        """Read the DPI of a source image using PIL.

        Returns the DPI value, or 96.0 as fallback.
        """
        try:
            from PIL import Image as PILImage

            with PILImage.open(img_path) as img:
                dpi_info = img.info.get("dpi")
                if dpi_info and len(dpi_info) >= 2:
                    dpi = max(dpi_info[0], dpi_info[1], 72.0)
                    logger.debug("Image DPI: %.1f (from %s)", dpi, img_path)
                    return dpi
        except Exception:
            pass
        logger.debug("Could not read DPI from '%s', falling back to 96.0", img_path)
        return 96.0

    @staticmethod
    def _build_layers(blk_list: List, dpi: float = 96.0) -> List[Dict]:
        """Convert TextBlock list → list of JS layer dicts.

        Args:
            blk_list: text blocks for this page.
            dpi: DPI of the source image, used to compute correct font point sizes.
        """
        layers = []
        for idx, blk in enumerate(blk_list):
            if not blk.translation:
                continue
            ff = blk.fontformat
            x1, y1, _x2, _y2 = blk.xyxy

            # Resolve font (static map only — no PS font list available)
            resolved, _ = resolve_font_name(ff.font_family, ps_available=None)

            # Font size in points, corrected for the source image's actual DPI.
            # ff.font_size is stored in logical pixels (96 DPI); PS expects points.
            size_pt = ff.font_size * 72.0 / dpi

            # Shadow angle from offset direction
            ox, oy = ff.shadow_offset
            shadow_angle = (math.degrees(math.atan2(oy, ox)) % 360) if ff.shadow_radius > 0 else 0

            # Shadow distance: offset magnitude proportional to font size
            shadow_distance = (
                math.hypot(ox, oy) * ff.font_size * 0.1
                if ff.shadow_radius > 0
                else 0
            )

            layers.append(
                {
                    "name": f"text_{idx:02d}_{blk.translation[:20].replace(chr(10),' ').replace(chr(13),'')}",
                    "text": blk.translation,
                    "font": resolved,
                    "size_pt": size_pt,
                    "color": ff.foreground_color(),
                    "bold": ff.bold,
                    "italic": ff.italic,
                    "underline": ff.underline,
                    "alignment": ff.alignment,
                    "vertical": ff.vertical,
                    "x": x1,
                    "y": y1,
                    "opacity": ff.opacity,
                    # stroke
                    "stroke_size": (
                        max(ff.stroke_width * ff.font_size * 0.5, 0.5)
                        if ff.stroke_width > 0
                        else 0
                    ),
                    "stroke_color": ff.stroke_color() if ff.stroke_width > 0 else [0, 0, 0],
                    # shadow
                    "shadow_blur": (
                        max(ff.shadow_radius * ff.font_size, 0.5)
                        if ff.shadow_radius > 0
                        else 0
                    ),
                    "shadow_opacity": (
                        int(ff.shadow_strength * 100)
                        if ff.shadow_strength > 0
                        else 0
                    ),
                    "shadow_distance": shadow_distance,
                    "shadow_color": ff.shadow_color,
                    "shadow_angle": shadow_angle,
                }
            )

        return layers

    @staticmethod
    def _build_font_notes(proj: ProjImgTrans, page_name: str) -> str:
        """Generate JS comments noting which fonts may need manual adjustment."""
        blk_list = proj.pages.get(page_name, [])
        families: Set[str] = set()
        for blk in blk_list:
            families.add(blk.fontformat.font_family)

        lines = ["// Font compatibility notes:"]
        for fam in sorted(families):
            mapped = QT_TO_PS_FONT_MAP.get(fam, fam)
            if mapped != fam:
                lines.append(f"//   '{fam}' → '{mapped}' (auto-mapped)")
            else:
                lines.append(
                    f"//   '{fam}' — verify this font is installed in Photoshop"
                )
        lines.append("//")
        return "\n".join(lines)
